//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimbeertoniRaidTool.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HimbeertoniRaidTool.Common.Localization.CommonLoc", typeof(CommonLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string DataType_Character {
            get {
                return ResourceManager.GetString("DataType_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gear set.
        /// </summary>
        public static string DataTypeName_GearSet {
            get {
                return ResourceManager.GetString("DataTypeName_GearSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string DataTypeName_item {
            get {
                return ResourceManager.GetString("DataTypeName_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item (gear).
        /// </summary>
        public static string DataTypeName_item_gear {
            get {
                return ResourceManager.GetString("DataTypeName_item_gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string DataTypeName_Job {
            get {
                return ResourceManager.GetString("DataTypeName_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materia.
        /// </summary>
        public static string DataTypeName_materia {
            get {
                return ResourceManager.GetString("DataTypeName_materia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to player.
        /// </summary>
        public static string DataTypeName_Player {
            get {
                return ResourceManager.GetString("DataTypeName_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raid group.
        /// </summary>
        public static string DataTypeName_RaidGroup {
            get {
                return ResourceManager.GetString("DataTypeName_RaidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Realm Reborn.
        /// </summary>
        public static string Expansion_ARR {
            get {
                return ResourceManager.GetString("Expansion_ARR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawntrail.
        /// </summary>
        public static string Expansion_DT {
            get {
                return ResourceManager.GetString("Expansion_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endwalker.
        /// </summary>
        public static string Expansion_EW {
            get {
                return ResourceManager.GetString("Expansion_EW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavensward.
        /// </summary>
        public static string Expansion_HW {
            get {
                return ResourceManager.GetString("Expansion_HW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stormblood.
        /// </summary>
        public static string Expansion_SB {
            get {
                return ResourceManager.GetString("Expansion_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowbringers.
        /// </summary>
        public static string Expansion_ShB {
            get {
                return ResourceManager.GetString("Expansion_ShB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etro.gg.
        /// </summary>
        public static string GearManager_etro_gg {
            get {
                return ResourceManager.GetString("GearManager_etro.gg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local database.
        /// </summary>
        public static string GearManager_HrtLocal {
            get {
                return ResourceManager.GetString("GearManager_HrtLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XivGear.app.
        /// </summary>
        public static string GearManager_XivGear {
            get {
                return ResourceManager.GetString("GearManager_XivGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belt.
        /// </summary>
        public static string GearSlot_Belt {
            get {
                return ResourceManager.GetString("GearSlot_Belt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string GearSlot_Body {
            get {
                return ResourceManager.GetString("GearSlot_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracelet.
        /// </summary>
        public static string GearSlot_Bracelet {
            get {
                return ResourceManager.GetString("GearSlot_Bracelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earrings.
        /// </summary>
        public static string GearSlot_Earrings {
            get {
                return ResourceManager.GetString("GearSlot_Earrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        public static string GearSlot_Gloves {
            get {
                return ResourceManager.GetString("GearSlot_Gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string GearSlot_Head {
            get {
                return ResourceManager.GetString("GearSlot_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necklace.
        /// </summary>
        public static string GearSlot_Necklace {
            get {
                return ResourceManager.GetString("GearSlot_Necklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        public static string GearSlot_Ring {
            get {
                return ResourceManager.GetString("GearSlot_Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring (L).
        /// </summary>
        public static string GearSlot_Ring_L {
            get {
                return ResourceManager.GetString("GearSlot_Ring_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring (R).
        /// </summary>
        public static string GearSlot_Ring_R {
            get {
                return ResourceManager.GetString("GearSlot_Ring_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string GearSlot_Shield {
            get {
                return ResourceManager.GetString("GearSlot_Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        public static string GearSlot_Shoes {
            get {
                return ResourceManager.GetString("GearSlot_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Crystal.
        /// </summary>
        public static string GearSlot_SoulCrystal {
            get {
                return ResourceManager.GetString("GearSlot_SoulCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trousers.
        /// </summary>
        public static string GearSlot_Trousers {
            get {
                return ResourceManager.GetString("GearSlot_Trousers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        public static string GearSlot_Weapon {
            get {
                return ResourceManager.GetString("GearSlot_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        public static string GearSource_Alliance {
            get {
                return ResourceManager.GetString("GearSource_Alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tome.
        /// </summary>
        public static string GearSource_Tome {
            get {
                return ResourceManager.GetString("GearSource_Tome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string GearSource_Trial {
            get {
                return ResourceManager.GetString("GearSource_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Group.
        /// </summary>
        public static string GroupType_FullGroup {
            get {
                return ResourceManager.GetString("GroupType_FullGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupType_Group {
            get {
                return ResourceManager.GetString("GroupType_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo.
        /// </summary>
        public static string GroupType_Solo {
            get {
                return ResourceManager.GetString("GroupType_Solo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted.
        /// </summary>
        public static string ItemSource_Crafted {
            get {
                return ResourceManager.GetString("ItemSource_Crafted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon.
        /// </summary>
        public static string ItemSource_Dungeon {
            get {
                return ResourceManager.GetString("ItemSource_Dungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looted.
        /// </summary>
        public static string ItemSource_Loot {
            get {
                return ResourceManager.GetString("ItemSource_Loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        public static string ItemSource_Quest {
            get {
                return ResourceManager.GetString("ItemSource_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid.
        /// </summary>
        public static string ItemSource_Raid {
            get {
                return ResourceManager.GetString("ItemSource_Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relic.
        /// </summary>
        public static string ItemSource_Relic {
            get {
                return ResourceManager.GetString("ItemSource_Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string ItemSource_Shop {
            get {
                return ResourceManager.GetString("ItemSource_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string Month_Abrrev_April {
            get {
                return ResourceManager.GetString("Month_Abrrev_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string Month_Abrrev_August {
            get {
                return ResourceManager.GetString("Month_Abrrev_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string Month_Abrrev_December {
            get {
                return ResourceManager.GetString("Month_Abrrev_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string Month_Abrrev_February {
            get {
                return ResourceManager.GetString("Month_Abrrev_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string Month_Abrrev_January {
            get {
                return ResourceManager.GetString("Month_Abrrev_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string Month_Abrrev_July {
            get {
                return ResourceManager.GetString("Month_Abrrev_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string Month_Abrrev_June {
            get {
                return ResourceManager.GetString("Month_Abrrev_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string Month_Abrrev_March {
            get {
                return ResourceManager.GetString("Month_Abrrev_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Month_Abrrev_May {
            get {
                return ResourceManager.GetString("Month_Abrrev_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string Month_Abrrev_November {
            get {
                return ResourceManager.GetString("Month_Abrrev_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string Month_Abrrev_October {
            get {
                return ResourceManager.GetString("Month_Abrrev_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string Month_Abrrev_September {
            get {
                return ResourceManager.GetString("Month_Abrrev_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Month_April {
            get {
                return ResourceManager.GetString("Month_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Month_August {
            get {
                return ResourceManager.GetString("Month_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Month_December {
            get {
                return ResourceManager.GetString("Month_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Month_February {
            get {
                return ResourceManager.GetString("Month_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Month_January {
            get {
                return ResourceManager.GetString("Month_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Month_July {
            get {
                return ResourceManager.GetString("Month_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Month_June {
            get {
                return ResourceManager.GetString("Month_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Month_March {
            get {
                return ResourceManager.GetString("Month_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Month_May {
            get {
                return ResourceManager.GetString("Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Month_November {
            get {
                return ResourceManager.GetString("Month_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Month_October {
            get {
                return ResourceManager.GetString("Month_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Month_September {
            get {
                return ResourceManager.GetString("Month_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.A..
        /// </summary>
        public static string NotAvail_Abbrev {
            get {
                return ResourceManager.GetString("NotAvail_Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caster.
        /// </summary>
        public static string Role_Caster {
            get {
                return ResourceManager.GetString("Role_Caster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer.
        /// </summary>
        public static string Role_Healer {
            get {
                return ResourceManager.GetString("Role_Healer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Role_Melee {
            get {
                return ResourceManager.GetString("Role_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string Role_Ranged {
            get {
                return ResourceManager.GetString("Role_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string Role_Tank {
            get {
                return ResourceManager.GetString("Role_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Magic Potency.
        /// </summary>
        public static string StatType_AttackMagicPotency {
            get {
                return ResourceManager.GetString("StatType_AttackMagicPotency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttackPower.
        /// </summary>
        public static string StatType_AttackPower {
            get {
                return ResourceManager.GetString("StatType_AttackPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Hit.
        /// </summary>
        public static string StatType_Critical_Hit {
            get {
                return ResourceManager.GetString("StatType_Critical Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Hit Power.
        /// </summary>
        public static string StatType_Critical_Hit_Power {
            get {
                return ResourceManager.GetString("StatType_Critical Hit Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Damage.
        /// </summary>
        public static string StatType_CriticalDamage {
            get {
                return ResourceManager.GetString("StatType_CriticalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string StatType_Defense {
            get {
                return ResourceManager.GetString("StatType_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determination.
        /// </summary>
        public static string StatType_Determination {
            get {
                return ResourceManager.GetString("StatType_Determination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string StatType_Dexterity {
            get {
                return ResourceManager.GetString("StatType_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Hit.
        /// </summary>
        public static string StatType_Direct_Hit {
            get {
                return ResourceManager.GetString("StatType_Direct Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Magic Potency.
        /// </summary>
        public static string StatType_HealingMagicPotency {
            get {
                return ResourceManager.GetString("StatType_HealingMagicPotency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP.
        /// </summary>
        public static string StatType_HP {
            get {
                return ResourceManager.GetString("StatType_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string StatType_Intelligence {
            get {
                return ResourceManager.GetString("StatType_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Damage.
        /// </summary>
        public static string StatType_MagicalDamage {
            get {
                return ResourceManager.GetString("StatType_MagicalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Defense.
        /// </summary>
        public static string StatType_MagicalDefense {
            get {
                return ResourceManager.GetString("StatType_MagicalDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Damage.
        /// </summary>
        public static string StatType_MagicDamage {
            get {
                return ResourceManager.GetString("StatType_MagicDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Defense.
        /// </summary>
        public static string StatType_MagicDefense {
            get {
                return ResourceManager.GetString("StatType_MagicDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mind.
        /// </summary>
        public static string StatType_Mind {
            get {
                return ResourceManager.GetString("StatType_Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        public static string StatType_MP {
            get {
                return ResourceManager.GetString("StatType_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string StatType_None {
            get {
                return ResourceManager.GetString("StatType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Damage.
        /// </summary>
        public static string StatType_PhysicalDamage {
            get {
                return ResourceManager.GetString("StatType_PhysicalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string StatType_PhysicalDefense {
            get {
                return ResourceManager.GetString("StatType_PhysicalDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piety.
        /// </summary>
        public static string StatType_Piety {
            get {
                return ResourceManager.GetString("StatType_Piety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Speed.
        /// </summary>
        public static string StatType_Skill_Speed {
            get {
                return ResourceManager.GetString("StatType_Skill Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Speed.
        /// </summary>
        public static string StatType_SpellSpeed {
            get {
                return ResourceManager.GetString("StatType_SpellSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA / DoT multiplier.
        /// </summary>
        public static string StatType_SpsSksMultiplier {
            get {
                return ResourceManager.GetString("StatType_SpsSksMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string StatType_Strength {
            get {
                return ResourceManager.GetString("StatType_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenacity.
        /// </summary>
        public static string StatType_Tenacity {
            get {
                return ResourceManager.GetString("StatType_Tenacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        public static string StatType_Vitality {
            get {
                return ResourceManager.GetString("StatType_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRT.
        /// </summary>
        public static string StatTypeAbbrev_CriticalHit {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_CriticalHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DET.
        /// </summary>
        public static string StatTypeAbbrev_Determination {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Determination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEX.
        /// </summary>
        public static string StatTypeAbbrev_Dexterity {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DH.
        /// </summary>
        public static string StatTypeAbbrev_DirectHit {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_DirectHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT.
        /// </summary>
        public static string StatTypeAbbrev_Intelligence {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MND.
        /// </summary>
        public static string StatTypeAbbrev_Mind {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIE.
        /// </summary>
        public static string StatTypeAbbrev_Piety {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Piety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKS.
        /// </summary>
        public static string StatTypeAbbrev_SkillSpeed {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_SkillSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPS.
        /// </summary>
        public static string StatTypeAbbrev_SpellSpeed {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_SpellSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR.
        /// </summary>
        public static string StatTypeAbbrev_Strength {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEN.
        /// </summary>
        public static string StatTypeAbbrev_Tenacity {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Tenacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIT.
        /// </summary>
        public static string StatTypeAbbrev_Vitality {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        public static string undefined {
            get {
                return ResourceManager.GetString("undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string Weekday_Abbrev_Friday {
            get {
                return ResourceManager.GetString("Weekday_Abbrev_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Weekday_Abbrev_Monday {
            get {
                return ResourceManager.GetString("Weekday_Abbrev_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Weekday_Abbrev_Saturday {
            get {
                return ResourceManager.GetString("Weekday_Abbrev_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Weekday_Abbrev_Sunday {
            get {
                return ResourceManager.GetString("Weekday_Abbrev_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string Weekday_Abbrev_Thursday {
            get {
                return ResourceManager.GetString("Weekday_Abbrev_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Weekday_Abbrev_Tuesday {
            get {
                return ResourceManager.GetString("Weekday_Abbrev_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Weekday_Abbrev_Wednesday {
            get {
                return ResourceManager.GetString("Weekday_Abbrev_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Weekday_Friday {
            get {
                return ResourceManager.GetString("Weekday_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Weekday_Monday {
            get {
                return ResourceManager.GetString("Weekday_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Weekday_Saturday {
            get {
                return ResourceManager.GetString("Weekday_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Weekday_Sunday {
            get {
                return ResourceManager.GetString("Weekday_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Weekday_Thursday {
            get {
                return ResourceManager.GetString("Weekday_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Weekday_Tuesday {
            get {
                return ResourceManager.GetString("Weekday_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Weekday_Wednesday {
            get {
                return ResourceManager.GetString("Weekday_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
