//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimbeertoniRaidTool.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HimbeertoniRaidTool.Common.Localization.CommonLoc", typeof(CommonLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Realm Reborn.
        /// </summary>
        internal static string Expansion_ARR {
            get {
                return ResourceManager.GetString("Expansion_ARR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawntrail.
        /// </summary>
        internal static string Expansion_DT {
            get {
                return ResourceManager.GetString("Expansion_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endwalker.
        /// </summary>
        internal static string Expansion_EW {
            get {
                return ResourceManager.GetString("Expansion_EW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavensward.
        /// </summary>
        internal static string Expansion_HW {
            get {
                return ResourceManager.GetString("Expansion_HW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stormblood.
        /// </summary>
        internal static string Expansion_SB {
            get {
                return ResourceManager.GetString("Expansion_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowbringers.
        /// </summary>
        internal static string Expansion_ShB {
            get {
                return ResourceManager.GetString("Expansion_ShB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etro.gg.
        /// </summary>
        internal static string GearManager_etro_gg {
            get {
                return ResourceManager.GetString("GearManager_etro.gg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HimbeerToni Raid Tool.
        /// </summary>
        internal static string GearManager_HimbeerToniRaidTool {
            get {
                return ResourceManager.GetString("GearManager_HimbeerToniRaidTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belt.
        /// </summary>
        internal static string GearSlot_Belt {
            get {
                return ResourceManager.GetString("GearSlot_Belt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string GearSlot_Body {
            get {
                return ResourceManager.GetString("GearSlot_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracelet.
        /// </summary>
        internal static string GearSlot_Bracelet {
            get {
                return ResourceManager.GetString("GearSlot_Bracelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earrings.
        /// </summary>
        internal static string GearSlot_Earrings {
            get {
                return ResourceManager.GetString("GearSlot_Earrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        internal static string GearSlot_Gloves {
            get {
                return ResourceManager.GetString("GearSlot_Gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string GearSlot_Head {
            get {
                return ResourceManager.GetString("GearSlot_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necklace.
        /// </summary>
        internal static string GearSlot_Necklace {
            get {
                return ResourceManager.GetString("GearSlot_Necklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        internal static string GearSlot_Ring {
            get {
                return ResourceManager.GetString("GearSlot_Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring (L).
        /// </summary>
        internal static string GearSlot_Ring_L {
            get {
                return ResourceManager.GetString("GearSlot_Ring_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring (R).
        /// </summary>
        internal static string GearSlot_Ring_R {
            get {
                return ResourceManager.GetString("GearSlot_Ring_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        internal static string GearSlot_Shield {
            get {
                return ResourceManager.GetString("GearSlot_Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        internal static string GearSlot_Shoes {
            get {
                return ResourceManager.GetString("GearSlot_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Crystal.
        /// </summary>
        internal static string GearSlot_SoulCrystal {
            get {
                return ResourceManager.GetString("GearSlot_SoulCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trousers.
        /// </summary>
        internal static string GearSlot_Trousers {
            get {
                return ResourceManager.GetString("GearSlot_Trousers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string GearSlot_Weapon {
            get {
                return ResourceManager.GetString("GearSlot_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        internal static string GearSource_Alliance {
            get {
                return ResourceManager.GetString("GearSource_Alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tome.
        /// </summary>
        internal static string GearSource_Tome {
            get {
                return ResourceManager.GetString("GearSource_Tome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string GearSource_Trial {
            get {
                return ResourceManager.GetString("GearSource_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Group.
        /// </summary>
        internal static string GroupType_FullGroup {
            get {
                return ResourceManager.GetString("GroupType_FullGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string GroupType_Group {
            get {
                return ResourceManager.GetString("GroupType_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo.
        /// </summary>
        internal static string GroupType_Solo {
            get {
                return ResourceManager.GetString("GroupType_Solo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted.
        /// </summary>
        internal static string ItemSource_Crafted {
            get {
                return ResourceManager.GetString("ItemSource_Crafted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon.
        /// </summary>
        internal static string ItemSource_Dungeon {
            get {
                return ResourceManager.GetString("ItemSource_Dungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looted.
        /// </summary>
        internal static string ItemSource_Loot {
            get {
                return ResourceManager.GetString("ItemSource_Loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        internal static string ItemSource_Quest {
            get {
                return ResourceManager.GetString("ItemSource_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid.
        /// </summary>
        internal static string ItemSource_Raid {
            get {
                return ResourceManager.GetString("ItemSource_Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relic.
        /// </summary>
        internal static string ItemSource_Relic {
            get {
                return ResourceManager.GetString("ItemSource_Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string ItemSource_Shop {
            get {
                return ResourceManager.GetString("ItemSource_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caster.
        /// </summary>
        internal static string Role_Caster {
            get {
                return ResourceManager.GetString("Role_Caster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer.
        /// </summary>
        internal static string Role_Healer {
            get {
                return ResourceManager.GetString("Role_Healer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        internal static string Role_Melee {
            get {
                return ResourceManager.GetString("Role_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        internal static string Role_Ranged {
            get {
                return ResourceManager.GetString("Role_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        internal static string Role_Tank {
            get {
                return ResourceManager.GetString("Role_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Magic Potency.
        /// </summary>
        internal static string StatType_AttackMagicPotency {
            get {
                return ResourceManager.GetString("StatType_AttackMagicPotency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttackPower.
        /// </summary>
        internal static string StatType_AttackPower {
            get {
                return ResourceManager.GetString("StatType_AttackPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Hit.
        /// </summary>
        internal static string StatType_Critical_Hit {
            get {
                return ResourceManager.GetString("StatType_Critical Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Hit Power.
        /// </summary>
        internal static string StatType_Critical_Hit_Power {
            get {
                return ResourceManager.GetString("StatType_Critical Hit Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Damage.
        /// </summary>
        internal static string StatType_CriticalDamage {
            get {
                return ResourceManager.GetString("StatType_CriticalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        internal static string StatType_Defense {
            get {
                return ResourceManager.GetString("StatType_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determination.
        /// </summary>
        internal static string StatType_Determination {
            get {
                return ResourceManager.GetString("StatType_Determination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        internal static string StatType_Dexterity {
            get {
                return ResourceManager.GetString("StatType_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Hit.
        /// </summary>
        internal static string StatType_Direct_Hit {
            get {
                return ResourceManager.GetString("StatType_Direct Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Magic Potency.
        /// </summary>
        internal static string StatType_HealingMagicPotency {
            get {
                return ResourceManager.GetString("StatType_HealingMagicPotency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP.
        /// </summary>
        internal static string StatType_HP {
            get {
                return ResourceManager.GetString("StatType_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string StatType_Intelligence {
            get {
                return ResourceManager.GetString("StatType_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Damage.
        /// </summary>
        internal static string StatType_MagicalDamage {
            get {
                return ResourceManager.GetString("StatType_MagicalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Defense.
        /// </summary>
        internal static string StatType_MagicalDefense {
            get {
                return ResourceManager.GetString("StatType_MagicalDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Damage.
        /// </summary>
        internal static string StatType_MagicDamage {
            get {
                return ResourceManager.GetString("StatType_MagicDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Defense.
        /// </summary>
        internal static string StatType_MagicDefense {
            get {
                return ResourceManager.GetString("StatType_MagicDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mind.
        /// </summary>
        internal static string StatType_Mind {
            get {
                return ResourceManager.GetString("StatType_Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        internal static string StatType_MP {
            get {
                return ResourceManager.GetString("StatType_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string StatType_None {
            get {
                return ResourceManager.GetString("StatType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Damage.
        /// </summary>
        internal static string StatType_PhysicalDamage {
            get {
                return ResourceManager.GetString("StatType_PhysicalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        internal static string StatType_PhysicalDefense {
            get {
                return ResourceManager.GetString("StatType_PhysicalDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piety.
        /// </summary>
        internal static string StatType_Piety {
            get {
                return ResourceManager.GetString("StatType_Piety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Speed.
        /// </summary>
        internal static string StatType_Skill_Speed {
            get {
                return ResourceManager.GetString("StatType_Skill Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Speed.
        /// </summary>
        internal static string StatType_SpellSpeed {
            get {
                return ResourceManager.GetString("StatType_SpellSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA / DoT multiplier.
        /// </summary>
        internal static string StatType_SpsSksMultiplier {
            get {
                return ResourceManager.GetString("StatType_SpsSksMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string StatType_Strength {
            get {
                return ResourceManager.GetString("StatType_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenacity.
        /// </summary>
        internal static string StatType_Tenacity {
            get {
                return ResourceManager.GetString("StatType_Tenacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        internal static string StatType_Vitality {
            get {
                return ResourceManager.GetString("StatType_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRT.
        /// </summary>
        internal static string StatTypeAbbrev_CriticalHit {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_CriticalHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DET.
        /// </summary>
        internal static string StatTypeAbbrev_Determination {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Determination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEX.
        /// </summary>
        internal static string StatTypeAbbrev_Dexterity {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DH.
        /// </summary>
        internal static string StatTypeAbbrev_DirectHit {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_DirectHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT.
        /// </summary>
        internal static string StatTypeAbbrev_Intelligence {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MND.
        /// </summary>
        internal static string StatTypeAbbrev_Mind {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIE.
        /// </summary>
        internal static string StatTypeAbbrev_Piety {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Piety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKS.
        /// </summary>
        internal static string StatTypeAbbrev_SkillSpeed {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_SkillSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPS.
        /// </summary>
        internal static string StatTypeAbbrev_SpellSpeed {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_SpellSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR.
        /// </summary>
        internal static string StatTypeAbbrev_Strength {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEN.
        /// </summary>
        internal static string StatTypeAbbrev_Tenacity {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Tenacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIT.
        /// </summary>
        internal static string StatTypeAbbrev_Vitality {
            get {
                return ResourceManager.GetString("StatTypeAbbrev_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        internal static string undefined {
            get {
                return ResourceManager.GetString("undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
